### ISSUE TITLE
Некорректная работа индикатора Маркет Профиль.

### ISSUE THREAD

**Issue by ConstantinGugin** [EarnForex/MarketProfile#11]
На таймфрейме м5, в режиме "Прямоугольник", индикатор работает некорректно. С очень сильной задержкой, в несколько свечей. 
Так ведь не должно быть, если он подсчитывает сколько раз цена посещала ту или иную цену. 
![123](https://github.com/EarnForex/MarketProfile/assets/24586626/2a9b8eb4-8f6b-4dfd-8c66-8009b7e4ddba)
Цена уже ушла в диапазон 4555, и лишь тогда медиана переместилась на 4548
![124](https://github.com/EarnForex/MarketProfile/assets/24586626/8a02e41d-008c-4ac8-b236-5dc2030e99be)

**Comment by EarnForex** [comment]
Здравствуйте, Константин!

Не очень понятно, в чем вы видите проблему. Не могли бы вы объяснить поподробнее?

**Comment by ConstantinGugin** [comment]
Ну смотрите. Квадрат уже ушёл на несколько свечей вправо и лишь тогда медиана заняла новое положение, на новом, более высоком уровне цены. А на тогда когда квадрат был в том месте. То есть получается задержка с подсчётом.
![123](https://github.com/EarnForex/MarketProfile/assets/24586626/b1269df8-d11a-4c25-9c94-08b9bdd88af2)

**Comment by ConstantinGugin** [comment]
Не тот рисунок загрузил. ( 
![123](https://github.com/EarnForex/MarketProfile/assets/24586626/49716c37-a7b3-483a-8fd7-69059447fd63)

**Comment by EarnForex** [comment]
Я так понимаю, что длина гистограммы в этих точках одинаковая, а медиана переходит на верхнюю точку только потому, что с новыми свечами там получается более равномерное распределение точек сверху и точек снизу.

**Comment by ConstantinGugin** [comment]
Блин. Вот только что ещё раз двигал прямоугольник. 
Медиана сместилась на указанный уровень, когда прямоугольник переместился на следующую свечу, после той, под которую передвинулась медиана. 
От чего это может зависеть ??? Голову сломал. Ничего ведь не поменялось. Никаких сайтов не отключал. Все как и было когда писал предыдущий пост. ( 
![125](https://github.com/EarnForex/MarketProfile/assets/24586626/0bba5a5f-7ba0-46a3-82ce-4e5a98f13669)

**Comment by ConstantinGugin** [comment]
А вот опять задержка. Что то с арифметикой подсчёта. И, обратите внимание на то, что гистограмма уже показывает, где должна проходить медиана, но медиана ещё не сместилась на новый уровень.
![126](https://github.com/EarnForex/MarketProfile/assets/24586626/6fe0a02f-fed0-473a-9509-d23bc23b9600)

**Comment by EarnForex** [comment]
> Блин. Вот только что ещё раз двигал прямоугольник. Медиана сместилась на указанный уровень, когда прямоугольник переместился на следующую свечу, после той, под которую передвинулась медиана. От чего это может зависеть ??? Голову сломал. Ничего ведь не поменялось. Никаких сайтов не отключал. Все как и было когда писал предыдущий пост. ( То есть, по сути, сейчас сработало нормально. Такое и ранее бывало. Ничего не делаешь, а то вовремя смещается (медиана), то с задержкой.. ![125](https://user-images.githubusercontent.com/24586626/268239453-0bba5a5f-7ba0-46a3-82ce-4e5a98f13669.png)

Здесь у вас прямоугольник не захватил нижний кусок графика.

**Comment by EarnForex** [comment]
> А вот опять задержка. Что то с арифметикой подсчёта. И, обратите внимание на то, что гистограмма уже показывает, где должна проходить медиана, но медиана ещё не сместилась на новый уровень. ![126](https://user-images.githubusercontent.com/24586626/268243095-e983a94a-cd92-43e2-b12d-3db8906ce45e.png)

Судя по всему, гистограмма там точно такой же длины как и на старом месте. Попробуйте приблизить график.

**Comment by ConstantinGugin** [comment]
Не, не. ВВерху гистограмма чуть длиннее. Проверял. На МТ 4 есть же перекрестие.
Увеличил и поставил перекрестие. Чётко видно, что сверху гистограма длиннее.
И вот, в Пайнте, кинул вертикаль. Тоже видно, что сверху длиннее.
![126](https://github.com/EarnForex/MarketProfile/assets/24586626/fd300c06-db02-46fc-9393-86e6623298d8)

**Comment by EarnForex** [comment]
Если вы приблизите, то увидите небольшую черточку под медианой - она той же длины, что и верхния гистограмма и доходит до вертикальной черты, которую вы нарисовали. Если вы поменяете цвет медианы на какой-то другой (например, зеленый или желтый), то вам будет легче заметить этот отрезок гистограммы, так как сейчас он почти сливается с медианой.

**Comment by EarnForex** [comment]
Получилось у вас разобраться в этой ситуации?

**Comment by ConstantinGugin** [comment]
Ну вот же. Смотрите.
Объём сместился, а медиана запаздывает.
![11](https://github.com/EarnForex/MarketProfile/assets/24586626/a65d7da4-d875-413c-a5b4-b61bed77d8fc)
![12](https://github.com/EarnForex/MarketProfile/assets/24586626/581978f1-66a6-43e7-a4d7-d39362b6f7e1)

**Comment by EarnForex** [comment]
Да, на этих скриншотах уже точно видно. Пришлите, пожалуйста, название брокера, чтобы можно было воспроизвести и понять, в чем ошибка.

**Comment by ConstantinGugin** [comment]
добрый вечер. 
Это демо счёт у Герчика.
На АMarkets тоже самое.
![13](https://github.com/EarnForex/MarketProfile/assets/24586626/ecc7d530-8868-4a0e-8e90-23bca6a95963)

**Comment by EarnForex** [comment]
На AMarkets - там как раз есть отросточек такой же длины как и верхняя гистограмма. Очень хорошо видно, если отключить Медиану (цвет None):
![image](https://github.com/EarnForex/MarketProfile/assets/48102957/9dc93e7f-2661-4460-8d1e-ff02598e1daa)

Сейчас зарегистрируюсь у Герчика и попробую там посмотреть.

**Comment by EarnForex** [comment]
Что-то я у Герчика не нахожу символа с названием S&P500.

**Comment by ConstantinGugin** [comment]
Здравствуйте.
Похоже мне надо извиниться. 
Все рисунки, что представлены, это с АМаркетса.
У Герчика S&P 500 нет. Есть SPY и SPX 500. 
Ещё видел несоответствие на акциях, но не заскринил. Так что впредь буду внимательнее отслеживать гистограмму. Может и там тоже ошибался. 
Спасибо, что отреагировали и поучаствовали в разборе рисунков. )

**Comment by EarnForex** [comment]
У Pepperstone есть.

**Comment by ConstantinGugin** [comment]
Здравствуйте.
На S&P 500, индикатор на разных ТФ показывает разные уровни. 
Так ведь быть не должно !?
![2](https://github.com/EarnForex/MarketProfile/assets/24586626/f630850c-1f3c-4270-aae8-38a39c4df363)
![3](https://github.com/EarnForex/MarketProfile/assets/24586626/c59bc83f-9f18-449d-b746-71be41de4dc8)

**Comment by EarnForex** [comment]
Здравствуйте!

Такое запросто может быть, так как профиль строится по барам, а они - разные на разных таймфреймах.
