### ISSUE TITLE
I always get stuck when using the following operations. What is the reason? How do I solve the situation of being stuck?

### ISSUE THREAD

**Issue by liuainlp** [EarnForex/MarketProfile#13]
I always get stuck when using the following operations. What is the reason? How do I solve the situation of being stuck?
![image](https://github.com/EarnForex/MarketProfile/assets/105497144/c927fd3f-c603-4590-8cfe-2a86c3170d16)

**Comment by EarnForex** [comment]
Stuck how? Do you add a rectangle session and the platform freezes completely? Or what do you mean?

**Comment by liuainlp** [comment]
es, I set the parameter session to Rectangle. After manually drawing a rectangular session, the entire Mt4 trading system will get stuck and unable to operate. Occasionally, it can succeed on the five minute chart, but cycles longer than 5 minutes will get stuck and unable to operate. Do I know the reason?

Yes, I set the parameter session to Rectangle. After manually drawing a rectangular session, the entire Mt4 trading system will get stuck and unable to operate. Occasionally, it can succeed on the five minute chart, but cycles longer than 5 minutes will get stuck and unable to operate. Do I know the reason?

**Comment by liuainlp** [comment]
Yes, I set the parameter session to Rectangle. After manually drawing a rectangular session, the entire Mt4 trading system will get stuck and unable to operate. Occasionally, it can succeed on the five minute chart, but cycles longer than 5 minutes will get stuck and unable to operate. Do I know the reason?

**Comment by liuainlp** [comment]
Yes, I set the parameter session to Rectangle. After manually drawing a rectangular session, the entire Mt4 trading system will get stuck and unable to operate. Occasionally, it can succeed on the five minute chart, but cycles longer than 5 minutes will get stuck and unable to operatYe. Do I know the reason?

Yes, I set the parameter session to Rectangle. After manually drawing a rectangular session, the entire Mt4 trading system will get stuck and unable to operate. Occasionally, it can succeed on the five minute chart, but cycles longer than 5 minutes will get stuck and unable to operate. Do I know the reason?

**Comment by liuainlp** [comment]
Yes, I set the session parameter to Rectangle. After manually drawing a rectangle session, the entire MT4 trading system freezes and becomes unresponsive. Occasionally, it can succeed on the five-minute chart, but on timeframes greater than 5 minutes, it freezes directly and becomes unusable. I don't know the reason. I hope you can help me. Thank you.

**Comment by EarnForex** [comment]
Do you modify any other input settings? Or do you only change the session type?

Did you try adding the indicator to an empty chart, setting it to the Rectangle session type, and only then adding the actual rectangle (by pressing 'r' on your keyboard)?

You could also switch to the Experts tab on the Terminal subwindow before switching the session type, so that in case the platform freezes, you'd still be able to see the final messages in the log. Perhaps, there will be some error message that indicates the issue.

**Comment by liuainlp** [comment]
I followed the instructions on our official website's documentation, without making any other settings or changes. If I don't use rectangular sessions, there is no freezing issue when drawing automatically. However, when using rectangular sessions, occasionally I can operate successfully on the 5-minute timeframe chart, but frequent operations will also cause freezing, making the trading platform unusable. After using the 'R' key on timeframes greater than 5 minutes, it freezes directly. I don't know how to solve this problem, which seriously affects my customization of using the market overview indicator.
![image](https://github.com/EarnForex/MarketProfile/assets/105497144/306c817e-b789-4605-bc11-a4b120634ca7)
![image](https://github.com/EarnForex/MarketProfile/assets/105497144/0cf2d81e-7678-4944-9341-4882e63b2d17)
![image](https://github.com/EarnForex/MarketProfile/assets/105497144/b6c6e705-9aba-4d0c-a0cb-9b0f169a7a78)

**Comment by liuainlp** [comment]
请仔细阅读并理解下面文本，并将如下文本翻译形成英语：```您可以给我一个矩形会话操作的演示示例嘛？比如视频演示或者演示文档？首先排除我的操作错误。```

**Comment by liuainlp** [comment]
Could you provide me with a demonstration example of how to operate a rectangular session? For example, a video demonstration or a demo document? First, let's rule out any errors in my operation.

**Comment by EarnForex** [comment]
Here is the demo video:
https://www.youtube.com/watch?v=0qARqRcAWrk

Try increasing the PointMultiplier input parameter to 100. Please let me know if it fixes the freezing.

**Comment by liuainlp** [comment]
Thank you very much for your help. After changing the parameter to 100 as you suggested, the lagging effect has improved somewhat. I adjusted the parameter back to 500, and currently there is no lagging. I'm not sure what hardware resources you are using. Will this parameter affect the accuracy of the indicator? Does your community have better forex trading indicators? Or are there any latest research technical indicators? If so, even if it's a paid service, I would like to know. If possible, please let me know and I will provide you with my email address.

**Comment by EarnForex** [comment]
Actually, I'm running it on a 7-years old laptop. With PointMultiplier = 1, it lags somewhat on XAUUSD, but doesn't freeze. Perhaps you are running some other indicators that create additional chart objects? This might be slowing down the Market Profile a little.

All our indicators are completely free and are available here:
https://www.earnforex.com/metatrader-indicators/

**Comment by liuainlp** [comment]
Thank you

**Comment by liuainlp** [comment]
Where is the parameter description file for the Volume Profile indicator?

**Comment by EarnForex** [comment]
There is no parameter description file for the Volume Profile indicator. Please use the following forum topic for discussion of that indicator: https://www.earnforex.com/forum/threads/volume-profile.23262/
This is off-topic for this repository.
