### ISSUE TITLE
MT5 Version Slow & Freezing

### ISSUE THREAD

**Issue by ABACHOPPA** [EarnForex/MarketProfile#2]
I have an issue with the MT5 version which I do not have with the MT4 version, this has been ongoing for a few weeks now and isn't one I had previously and have been trying all sorts to diagnose it. It may be coincidence or not, but it all started to happen when MT5 did their latest update to build 2007, could there be a code clash maybe?

It happens even on a fresh install of MT5 where upon loading the whole terminal goes either incredibly slow and un-responsive or freeze up altogether with the only way of closing it being task manager. 

I've tried increasing the multiplier and throttle redraw, and reducing days down to even just 1. It's definitely not a hardware issue.

Let me know what details or information you would like me to provide as I'm unsure what to offer at the moment.

**Comment by EarnForex** [comment]
Try downloading the latest version (1.14) of the Market Profile and check if this is still an issue. Please let me know if that helped. Thanks!

**Comment by EarnForex** [comment]
I'm closing it as it is apparently stopped being an issue at some point.
