### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by igdomrachev** [EarnForex/MarketProfile#4]
НА МТ5 индикатор притормаживает, на нефти Бренд не работает!

**Comment by EarnForex** [comment]
Если притормаживает, есть способы с этим справиться:
1) Попробуйте увеличить параметр PointMultiplier до 10 или выше - чем выше, тем меньше будет графических объектов на графике. Оптимальное значение нужно подбирать в зависимости от инструмента и ваших предпочтений.
2) Можно изменить параметр ThrottleRedraw, сделав его равным 5 секундам. Это будет задерживать пересчет профиля и он меньше будет загружать компьютер.
3) Можно уменьшить количество сессий для которых делается расчет (SessionsToCount).
4) Можно сделать использовать цветовую схему (ColorScheme) Single color, которая рассчитывается быстрее.

По поводу Брента, чтобы вам помочь, мне для начала нужно знать, что выдавал индикатор во вкладке Эксперты (в самом низу терминала), когда вы его добавили на Брент. Если там совсем ничего, то нужен таймфрейм, название брокера и тип счета. Желательно еще .set файл с настройками, с которыми вы запускаете МП.

**Comment by EarnForex** [comment]
Should be fixed in 1.146 Beta.

**Comment by igdomrachev** [comment]
Значение Point of Control и Value Area линии не продливаются!

**Comment by EarnForex** [comment]
Попробуйте 1.147 Beta. Должно работать.

**Comment by igdomrachev** [comment]
Все работает! Спасибо.
