### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by igdomrachev** [EarnForex/MarketProfile#5]
Выдавал индикатор во вкладке Эксперты ; 2020.07.08 21:06:06.330	MarketProfile (BR-8.20,M5)	array out of range in 'MarketProfile.mq5' (1603,53)
Брокер "Открытие"

**Comment by EarnForex** [comment]
Спасибо! Файл .set с настройками индикатора, которые вы использовали в том случае, сможете тут прикрепить? Его можно сохранить на экране изменения параметров индикатора.

И я правильно понимаю, что речь идет об индикаторе версии 1.145?

**Comment by igdomrachev** [comment]
Да, индикатор версии 1.145
[Профит рама.zip](https://github.com/EarnForex/MarketProfile/files/4892280/default.zip)

**Comment by EarnForex** [comment]
Спасибо! Но что-то у меня пока не получается воспроизвести ошибку. Тут конечно еще много зависит от числа и расположения прямоугольников, которые вы задаете для отрисовки. У вас индикатор всегда сразу выдает ошибку, как только вы его добавляете на график Брента? Или после того, как что-то делаете с прямоугольником?

**Comment by igdomrachev** [comment]
После того, как что-то делаю с прямоугольником.

**Comment by EarnForex** [comment]
Should be fixed in 1.146 Beta.
