### ISSUE TITLE
session input option rectangle not showing in mt5

### ISSUE THREAD

**Issue by vyasbuddy** [EarnForex/MarketProfile#6]
Hi, 
I am a big fan of your work. Thanks for contributing to community with opensource indicators. I have observed that in market profile for mt5, session input option rectangle is not showing up. It is fine for mt4. Please resolve the issue. Thankyou
regards,
Vyas

**Comment by EarnForex** [comment]
Hello!

Are you sure you are using the latest version (1.15)? I just downloaded both .mq5 and .ex5 and both show fine the Rectangle option in the Session input parameter when I tried them.

**Comment by vyasbuddy** [comment]
Thankyou for the reply. I have used the 1.14 version earlier. Now I am using 1.15, in which rectangle option for session input is working fine.
